version: '3.7'

services:
  todo-list-api:
    build: todo-list-api/.
    ports:
      - "5051:8080"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "CONNECTIONSTRINGS__DEFAULT=Data Source=/sqlite_data/docker_todolist.db"
    volumes:
      - todo_list_data:/sqlite_data
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/health" ]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s
    depends_on:
      - db-migration

  db-migration:
    build:
      context: todo-list-api/.
      dockerfile: Dockerfile.migrate
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
      - "CONNECTIONSTRINGS__DEFAULT=Data Source=/sqlite_data/docker_todolist.db"
    volumes:
      - todo_list_data:/sqlite_data

  react-frontend:
    build: todo-list-web-react/.
    ports:
      - "3000:3000"
    depends_on:
      - todo-list-api

volumes:
  todo_list_data:
